import { Link } from "react-router-dom"
import { useAuth } from "../context/AuthContext"
import I from "../components/common/Icon"

const FEATURES = [
  { icon: "robot",     title: "AI Interviewer",    desc: "Meet Alex - your AI interviewer powered by LLaMA3. Conducts real conversations, asks follow-ups based on your answers, adapts difficulty in real-time." },
  { icon: "eye",       title: "Anti-Cheat System", desc: "Face tracking, eye movement detection, tab-switch alerts, copy-paste detection, and AI-generated answer detection with automatic disqualification." },
  { icon: "chart",     title: "Smart Scoring",     desc: "Multi-dimensional AI scoring: Technical Accuracy (40%), Relevance (25%), Clarity (20%), Depth (15%) with weighted topic scoring." },
  { icon: "doc",       title: "Detailed Reports",  desc: "Comprehensive reports with strengths, weaknesses, per-question breakdown, cheat logs, and hiring recommendations generated by AI." },
  { icon: "target",    title: "Mock Practice",     desc: "Candidates can practice unlimited mock interviews for any role before the real thing. Instant AI feedback on every answer." },
  { icon: "lightning",  title: "Real-time Updates", desc: "Live WebSocket updates, instant scoring, real-time cheat detection alerts, and automatic report generation upon completion." }
]

const STEPS = [
  { num: "01", icon: "pencil",    title: "Post Job Description",  desc: "Upload your JD and let AI automatically extract interview topics, assign weightages, and create a structured interview plan." },
  { num: "02", icon: "check",     title: "Review & Activate",     desc: "Review AI-generated topics, adjust weightages and difficulty, then activate the interview with one click." },
  { num: "03", icon: "mail",      title: "Invite Candidates",     desc: "Invite candidates by email. They get a unique session token and can join the interview from any browser." },
  { num: "04", icon: "robot",     title: "AI Conducts Interview", desc: "Alex AI interviews each candidate with personalized questions, follow-ups, and real-time cheating monitoring." },
  { num: "05", icon: "chart",     title: "Get Ranked Results",    desc: "Instant scores, percentile rankings, detailed reports, and hiring recommendations for every candidate." }
]

const Landing = () => {
  const { user } = useAuth()
  const dashPath = !user ? "/login" : user.role === "company" ? "/company" : user.role === "admin" ? "/admin" : "/candidate"

  return (
    <div className="min-h-screen bg-slate-900 overflow-x-hidden">

      {/* HERO */}
      <section className="relative min-h-screen flex flex-col items-center justify-center text-center px-6 py-24">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl" />
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl" />
        </div>

        <div className="relative z-10 max-w-5xl mx-auto">
          <div className="inline-flex items-center gap-2 bg-blue-900/40 border border-blue-700/50 text-blue-300 text-sm px-5 py-2 rounded-full mb-8">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
            Powered by Groq LLaMA3 AI - 100% Free
          </div>

          <h1 className="text-6xl md:text-8xl font-black text-white mb-6 leading-tight tracking-tight">
            AI-Powered
            <br />
            <span className="bg-gradient-to-r from-blue-400 via-blue-500 to-purple-500 bg-clip-text text-transparent">
              Interviews
            </span>
          </h1>

          <p className="text-xl md:text-2xl text-slate-400 max-w-3xl mx-auto mb-12 leading-relaxed">
            Replace human interviewers with AI. Post a JD, let AI conduct real interviews,
            detect cheating, score candidates automatically, and get ranked reports instantly.
          </p>

          <div className="flex flex-wrap gap-4 justify-center mb-16">
            {user ? (
              <Link to={dashPath} className="bg-blue-600 hover:bg-blue-500 text-white font-bold px-10 py-4 rounded-2xl text-lg transition-all shadow-lg shadow-blue-500/25 hover:scale-105">
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link to="/register" className="bg-blue-600 hover:bg-blue-500 text-white font-bold px-10 py-4 rounded-2xl text-lg transition-all shadow-lg shadow-blue-500/25 hover:scale-105">
                  Get Started Free
                </Link>
                <Link to="/login" className="bg-slate-800 hover:bg-slate-700 border border-slate-600 text-white font-bold px-10 py-4 rounded-2xl text-lg transition-all hover:border-slate-500">
                  Sign In
                </Link>
              </>
            )}
          </div>

          <div className="flex flex-wrap justify-center gap-8 md:gap-16">
            {[
              { val: "100%", label: "Automated" },
              { val: "0",    label: "Human Bias" },
              { val: "24/7", label: "Available" },
              { val: "<1s",  label: "AI Response" },
              { val: "Free", label: "Forever" }
            ].map(s => (
              <div key={s.label} className="text-center">
                <div className="text-3xl md:text-4xl font-black text-blue-400">{s.val}</div>
                <div className="text-slate-500 text-sm mt-1">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="px-6 py-24 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-black text-white mb-4">Everything You Need</h2>
          <p className="text-slate-400 text-xl max-w-2xl mx-auto">A complete AI interview platform with every feature for fair, efficient, bias-free interviews.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f, i) => (
            <div key={i} className="group bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 hover:border-blue-600/50 hover:bg-slate-800 transition-all duration-300 hover:-translate-y-1">
              <div className="w-14 h-14 bg-slate-700 group-hover:bg-blue-900/50 rounded-2xl flex items-center justify-center mb-5 transition-all">
                <I name={f.icon} size={6} className="text-slate-400 group-hover:text-blue-400 transition-colors" />
              </div>
              <h3 className="text-white font-bold text-xl mb-3 group-hover:text-blue-400 transition-colors">{f.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="px-6 py-24 bg-slate-800/30 border-y border-slate-800">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-black text-white mb-4">How It Works</h2>
            <p className="text-slate-400 text-xl">From job posting to hired candidate in 5 simple steps</p>
          </div>
          <div className="space-y-4">
            {STEPS.map((s, i) => (
              <div key={i} className="flex items-start gap-6 p-6 bg-slate-800/50 rounded-2xl border border-slate-700/50 hover:border-slate-600 transition-all">
                <div className="flex-shrink-0 w-16 h-16 bg-blue-900/30 border-2 border-blue-700/50 rounded-2xl flex flex-col items-center justify-center">
                  <span className="text-blue-400 text-xs font-bold">{s.num}</span>
                  <I name={s.icon} size={5} className="text-blue-400" />
                </div>
                <div>
                  <h3 className="text-white font-bold text-xl mb-1">{s.title}</h3>
                  <p className="text-slate-400 leading-relaxed">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FOR WHO */}
      <section className="px-6 py-24 max-w-6xl mx-auto">
        <h2 className="text-4xl font-black text-white text-center mb-12">Built For Everyone</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            { icon: "building", title: "Companies & HR", badge: "For Employers", color: "border-blue-700/50 hover:border-blue-500",
              features: ["Post unlimited job interviews","AI auto-generates questions from JD","Invite unlimited candidates","Real-time cheating monitoring","Ranked candidate reports","Hiring recommendation AI"] },
            { icon: "target", title: "Job Candidates", badge: "For Job Seekers", color: "border-green-700/50 hover:border-green-500",
              features: ["Join interviews with unique token","Real-time AI conversation","Voice-to-text answer input","Instant score after interview","Detailed performance report","Practice unlimited mock interviews"] },
            { icon: "shield", title: "System Admins", badge: "For Admins", color: "border-purple-700/50 hover:border-purple-500",
              features: ["Full user management","System-wide statistics","Monitor all interviews","Activate/deactivate accounts","View cheat reports","Database management"] }
          ].map((card, i) => (
            <div key={i} className={"bg-slate-800/50 border rounded-2xl p-6 transition-all duration-300 " + card.color}>
              <I name={card.icon} size={8} className="text-slate-400 mb-4" />
              <span className="badge-blue text-xs">{card.badge}</span>
              <h3 className="text-white font-bold text-xl mt-3 mb-4">{card.title}</h3>
              <ul className="space-y-2">
                {card.features.map((f, j) => (
                  <li key={j} className="flex items-center gap-2 text-slate-400 text-sm">
                    <I name="check" size={3} className="text-green-400 flex-shrink-0" /> {f}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* TECH STACK */}
      <section className="px-6 py-16 bg-slate-800/30 border-y border-slate-800">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-slate-500 text-sm font-medium uppercase tracking-wider mb-6">Built with open-source technology</p>
          <div className="flex flex-wrap justify-center gap-3">
            {["Groq LLaMA3 AI","React 18","Flask","SQLite","WebSocket","Web Speech API","face-api.js","Tailwind CSS","JWT Auth","Python"].map(t => (
              <span key={t} className="bg-slate-800 border border-slate-700 text-slate-400 text-sm px-4 py-2 rounded-xl">{t}</span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-24 text-center">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-black text-white mb-6">Start Hiring Smarter Today</h2>
          <p className="text-slate-400 text-xl mb-10">Free forever. No credit card. No limits.</p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Link to="/register" className="bg-blue-600 hover:bg-blue-500 text-white font-bold px-12 py-5 rounded-2xl text-xl transition-all shadow-xl shadow-blue-500/25 hover:scale-105">
              Get Started Free
            </Link>
            <Link to="/login" className="border border-slate-600 hover:border-slate-400 text-slate-300 hover:text-white font-bold px-12 py-5 rounded-2xl text-xl transition-all">
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800 px-6 py-8">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold text-sm">AI</div>
            <span className="text-white font-bold">InterviewAI</span>
          </div>
          <p className="text-slate-500 text-sm">Built with Groq LLaMA3, React, Flask, SQLite - 100% Open Source</p>
          <div className="flex gap-4">
            <Link to="/login" className="text-slate-500 hover:text-white text-sm transition-colors">Login</Link>
            <Link to="/register" className="text-slate-500 hover:text-white text-sm transition-colors">Register</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
export default Landing